name: CI
on:
  push:
    branches:
      - main
jobs:
  Main_branch:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Building docker image
        run: docker build ./podsticarijum_backend/ -t codeforacause/podsticarijum-app:${{ github.run_number }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pushing docker image to CR
        run: docker push codeforacause/podsticarijum-app:${{ github.run_number }}
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**/podsticarijum_backend/docker-compose.podsticarijum.yaml"]'
        env:
          TAG_NUMBER: "${{ github.run_number }}"
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./podsticarijum_backend/docker-compose.podsticarijum.yaml"
          target: "./Projects/podsticarijum-app/"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: docker-compose -f ./Projects/podsticarijum-app/podsticarijum_backend/docker-compose.podsticarijum.yaml up -d